"""create users and tags and posts and comments model

Revision ID: 37d2db334ca3
Revises: 381d9242bdd4
Create Date: 2024-05-14 16:32:34.436859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37d2db334ca3'
down_revision = '381d9242bdd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('local_time')

    # ### end Alembic commands ###
