"""create users and tags and posts and comments model

Revision ID: 381d9242bdd4
Revises: cb232a4472e6
Create Date: 2024-05-14 16:06:33.978887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '381d9242bdd4'
down_revision = 'cb232a4472e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('commenter_name', sa.Text(), nullable=False),
    sa.Column('commenter_email', sa.Text(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###
