"""create posts model

Revision ID: 72279b4cd57a
Revises: e3b32f248faa
Create Date: 2024-05-16 00:37:54.942595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72279b4cd57a'
down_revision = 'e3b32f248faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('local_time')

    # ### end Alembic commands ###
