"""create posts model

Revision ID: e3b32f248faa
Revises: 37d2db334ca3
Create Date: 2024-05-16 00:24:07.680515

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e3b32f248faa'
down_revision = '37d2db334ca3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('local_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_time', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
